env = DefaultEnvironment().Clone()

env.AppendUnique(CCFLAGS=['/DUNICODE', '/D_UNICODE']) # both are needed by the compiler
env.Append(CPPPATH = '#build/include')

files = Glob('misc/*.cc') + [
    'isc/hmacsha.cc',
    'sys/eventfd.cc',
    'sys/ioctl.cc',
    'sys/resource.cc',
    'sys/time.cc',
    'sys/wait.cc',
    'posix_fcntl.cc',
    'posix_stdlib.cc',
    'posix_string.cc',
    'posix_time.cc',
    'endian.cc',
    'sched.cc',
    'strings.cc',
    'unistd.cc',
    'wmiutils.cc'
]

contrail_windows_lib = env.Library('contrail-windows', files)
env.Requires(contrail_windows_lib, '#build/include/boost')
env.Install('#build/lib', 'contrail-windows.lib')
env.Alias('contrail-windows', '#/build/lib/contrail-windows.lib')
